name: youtube_iframe
description:  YouTube iFrame player 
version: 5.2.3


environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.7.0 <2.0.0'
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.2
  webview_flutter_wkwebview: ^3.16.2
  url_launcher: ^6.3.1
  youtube_player_iframe_web: ^3.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/player.html

  plugin:
    platforms:
      web:
        default_package: youtube_player_iframe_web

platforms:
  android:
  ios:
  macos:
  web:

